### ISSUE TITLE
pinout diagram

### ISSUE THREAD

**Issue by denisdemaisbr** [Harshal-Sakhale/TangNano_GoWin_FPGA_VGA_Signal_generator#1]
do you have the pinout diagram ?

**Comment by Harshal-Sakhale** [comment]
There is no circuit. We can directly connect the signals. Use some current limiting resistances for safety.

**Comment by Harshal-Sakhale** [comment]
I have added the circuit images for you 

https://github.com/Harshal-Sakhale/TangNano_GoWin_FPGA_VGA_Signal_generator/blob/main/test2.jpg

https://github.com/Harshal-Sakhale/TangNano_GoWin_FPGA_VGA_Signal_generator/blob/main/test1.jpg

Hope this helps 🙂
